name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - manual
env:
  SONAR_TOKEN: '75621cba6337eff300a0b42e8d68eb9d4cdbe709'
  SONAR_HOST_URL: 'http://brillioonesonar.eastus.cloudapp.azure.com:9000'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask-API
          pip install pytest  # Install pytest
        

      - name: Run Unit Tests
        run: pytest

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          sonar-token: ${{ env.SONAR_TOKEN }}
          project-key: GenAISonarQubeTesting
          project-name: GenAISonarQubeTesting
          project-version: 1.0
          sources: .
          exclusions: tests/**
          # Set other analysis parameters as required

      - name: Publish Artifacts
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --destination github-artifacts --source ./ --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
